apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: commit-stage-template
spec:
  arguments:
    parameters:
      - name: repo-owner
      - name: repo-name
      - name: git-commit
      - name: github-token
  templates:
    - name: all-steps
      dag:
        tasks:
          - name: setup-environment
            template: setup-environment

          - name: build
            template: build-app
            dependencies: [setup-environment]

          - name: test
            template: run-unit-tests
            dependencies: [build]

          - name: create-artifact
            template: create-artifact
            dependencies: [test]
            arguments:
              parameters:
                - name: repo-owner
                  value: "{{workflow.parameters.repo-owner}}"
                - name: repo-name
                  value: "{{workflow.parameters.repo-name}}"
                - name: git-commit
                  value: "{{workflow.parameters.git-commit}}"
                - name: github-token
                  value: "{{workflow.parameters.github-token}}"

    - name: setup-environment
      container:
        image: oven/bun:1
        command: [sh, -c]
        args:
          - |
            echo "Sätter upp miljö..."
            echo "Installerar paket via bun..."
            bun install

    - name: build-app
      container:
        image: oven/bun:1
        command: [sh, -c]
        args:
          - |
            echo "Bygger applikationen..."
            bun run build

    - name: run-unit-tests
      container:
        image: oven/bun:1
        command: [sh, -c]
        args:
          - |
            echo "Kör unit tests..."
            bun test

    - name: create-artifact
      inputs:
        parameters:
          - name: repo-owner
          - name: repo-name
          - name: git-commit
          - name: github-token
      container:
        image: docker:20
        command: [sh, -c]
        args:
          - |
            echo "Skapar image och pushar till GitHub Container Registry..."
            docker build -t ghcr.io/{{inputs.parameters.repo-owner}}/{{inputs.parameters.repo-name}}:{{inputs.parameters.git-commit}} .
            echo {{inputs.parameters.github-token}} | docker login ghcr.io -u {{inputs.parameters.repo-owner}} --password-stdin
            docker push ghcr.io/{{inputs.parameters.repo-owner}}/{{inputs.parameters.repo-name}}:{{inputs.parameters.git-commit}}
        # sh
