apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dagger
spec:
  templates:
    - name: dagger-run
      container:
        image: alpine:3.19
        command: [sh, -c]
        args:
          - |
            set -e
            echo "📦 Installing dependencies..."
            apk add --no-cache curl bash git

            echo "📥 Installing Dagger CLI..."
            curl -L https://dl.dagger.io/dagger/install.sh | sh
            export PATH="/root/.local/bin:$PATH"

            echo "⏳ Waiting for Dagger Engine..."
            until curl -s http://127.0.0.1:8080/query > /dev/null; do
              echo "waiting..."
              sleep 2
            done

            echo "⚡ Running Dagger commands..."
            dagger version
            dagger init --sdk go   # exempel på en pipeline-init
            dagger do build        # här kör du egna steg
        env:
          - name: DAGGER_SESSION_HOST
            value: "127.0.0.1:8080"
          - name: DAGGER_CLOUD_TOKEN
            valueFrom:
              secretKeyRef:
                name: dagger-cloud
                key: token
      sidecars:
        - name: dagger-engine
          image: registry.dagger.io/engine:v0.12.5
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /query
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 2
