---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: github-notify-template
spec:
  arguments:
    parameters:
      - name: repository_full_name
      - name: commit_sha
      - name: secret_name

  templates:
    - name: notify
      inputs:
        parameters:
          - name: repository_full_name
          - name: commit_sha
          - name: secret_name

      volumes:
        - name: github-secret
          secret:
            secretName: "{{inputs.parameters.secret_name}}"

      container:
        image: "ghcr.io/supportpal/github-gh-cli"
        command: [sh, -e, -c]
        volumeMounts:
          - name: github-secret
            mountPath: /secret/github
        args:
          - >-
            case "{{workflow.status}}" in
              "Running")
              state=pending
              ;;
              "Succeeded")
              state=success
              ;;
              "Failed")
              state=failure
              ;;
              *)
              state=error
              ;;
            esac;

            gh auth login --with-token < /secret/github/pat;
            gh api --method POST
            /repos/{{inputs.parameters.repository_full_name}}/statuses/{{inputs.parameters.commit_sha}}
            -f "state=$state"
            -f "description=CI: {{workflow.status}}"
            -f "target_url=https://argo-workflows.example.org/workflows/{{workflow.namespace}}/{{workflow.name}}"
            -f "context=ci"
