apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pipeline
spec:
  arguments:
    parameters:
      - name: source-folder
      - name: tag
      - name: repo-name
      - name: source-repo-url
      - name: registry-address
      - name: registry-username
      - name: registry-password-env
  entrypoint: ci
  templates:
    - name: ci
      dag:
        tasks:
          - name: ci
            template: dagger-ci
    - name: dagger-ci
      inputs:
        artifacts:
          - name: source-repo
            path: /source-repo
            git:
              # replace with your repository URL
              repo: https://$GITHUB_TOKEN@{{workflow.parameters.source-repo-url}}
              revision: "main"
          - name: deployment-pipeline
            path: /deployment-pipeline
            git:
              # replace with your repository URL
              repo: https://$GITHUB_TOKEN@github.com/simonbrundin/deployment-pipeline.git
              revision: "main"
          - name: dagger-cli
            path: /usr/local/bin
            mode: 0755
            http:
              # replace with the latest available version of Dagger for your platform
              url: https://github.com/dagger/dagger/releases/download/v0.18.16/dagger_v0.18.16_linux_arm64.tar.gz
      container:
        image: alpine:3.19
        command: [sh, -c]
        args:
          - |
            cd /deployment-pipeline/dagger-modules/pipeline
            dagger call ci \
              --image-name {{workflow.parameters.repo-name}} \
              --registry-address {{workflow.parameters.registry-address}} \
              --source-dir /source-repo/{{workflow.parameters.source-folder}} \
              --tag {{workflow.parameters.tag}} \
              --username {{workflow.parameters.registry-username}} \
              --secret ${{workflow.parameters.registry-password-env}}
        volumeMounts:
          - mountPath: /run/dagger
            name: dagger-socket
        env:
          # - name: DAGGER_SESSION_HOST
          #   value: "dagger-engine.dagger.svc.cluster.local:8080"
          - name: DAGGER_SESSION_HOST
            value: "127.0.0.1:8080"
          - name: "_EXPERIMENTAL_DAGGER_RUNNER_HOST"
            value: "unix:///run/dagger/engine.sock"
          - name: DAGGER_CLOUD_TOKEN
            valueFrom:
              secretKeyRef:
                name: dagger-cloud
                key: token
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-pat
                key: token
      sidecars:
        - name: dagger-engine
          # replace with the latest available version of Dagger for your platform
          image: registry.dagger.io/engine:v0.18.16
          securityContext:
            privileged: true
            capabilities:
              add:
                - ALL
          readinessProbe:
            exec:
              command: ["dagger", "core", "version"]
          volumeMounts:
            - mountPath: /run/dagger
              name: dagger-socket
            - mountPath: /var/lib/dagger
              name: dagger-storage
