apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pr-open-template
spec:
  templates:
    - name: all-steps
      dag:
        tasks:
          - name: say-hello
            template: say-hello
    - name: say-hello
      container:
        image: alpine:3.18
        command: [sh, -c]
        args:
          - echo "Hello!"
