// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/pipeline/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Pipeline) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Pipeline) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func (r MultiArchContainers) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Containers []*dagger.Container
		Platforms  []dagger.Platform
	}
	concrete.Containers = r.Containers
	concrete.Platforms = r.Platforms
	return json.Marshal(&concrete)
}

func (r *MultiArchContainers) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Containers []*dagger.Container
		Platforms  []dagger.Platform
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Containers = concrete.Containers
	r.Platforms = concrete.Platforms
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Pipeline":
		switch fnName {
		case "AcceptancePhase":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Pipeline).AcceptancePhase(&parent, ctx)
		case "BuildImage":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceDir *dagger.Directory
			if inputArgs["sourceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceDir"]), &sourceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceDir", err))
				}
			}
			return (*Pipeline).BuildImage(&parent, ctx, sourceDir)
		case "BuildMultiArchImage":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceDir *dagger.Directory
			if inputArgs["sourceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceDir"]), &sourceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceDir", err))
				}
			}
			return (*Pipeline).BuildMultiArchImage(&parent, ctx, sourceDir)
		case "CD":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Pipeline).CD(&parent)
		case "CommitPhase":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceDir *dagger.Directory
			if inputArgs["sourceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceDir"]), &sourceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceDir", err))
				}
			}
			var registryAddress string
			if inputArgs["registryAddress"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryAddress"]), &registryAddress)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryAddress", err))
				}
			}
			var imageName string
			if inputArgs["imageName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["imageName"]), &imageName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg imageName", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			var multiArch bool
			if inputArgs["multiArch"] != nil {
				err = json.Unmarshal([]byte(inputArgs["multiArch"]), &multiArch)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg multiArch", err))
				}
			}
			return (*Pipeline).CommitPhase(&parent, sourceDir, registryAddress, imageName, username, multiArch)
		case "GetCommitsSinceTag":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceDir *dagger.Directory
			if inputArgs["sourceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceDir"]), &sourceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceDir", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			return (*Pipeline).GetCommitsSinceTag(&parent, ctx, sourceDir, tag)
		case "GetLatestTag":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var sourceDir *dagger.Directory
			if inputArgs["sourceDir"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sourceDir"]), &sourceDir)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sourceDir", err))
				}
			}
			return (*Pipeline).GetLatestTag(&parent, ctx, sourceDir)
		case "PushImages":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var containers []*dagger.Container
			if inputArgs["containers"] != nil {
				err = json.Unmarshal([]byte(inputArgs["containers"]), &containers)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg containers", err))
				}
			}
			var registryAddress string
			if inputArgs["registryAddress"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryAddress"]), &registryAddress)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryAddress", err))
				}
			}
			var imageName string
			if inputArgs["imageName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["imageName"]), &imageName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg imageName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			return (*Pipeline).PushImages(&parent, ctx, containers, registryAddress, imageName, tag, username)
		case "RunTests":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Pipeline).RunTests(&parent, ctx)
		case "SemVerBump":
			var parent Pipeline
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var currentVersion string
			if inputArgs["currentVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["currentVersion"]), &currentVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg currentVersion", err))
				}
			}
			var commitMessage string
			if inputArgs["commitMessage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["commitMessage"]), &commitMessage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg commitMessage", err))
				}
			}
			return (*Pipeline).SemVerBump(&parent, currentVersion, commitMessage)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
