name: Acceptance Phase

on:
  workflow_call:
    inputs:
      source-dir:
        required: false
        default: "."
        type: string

jobs:
  acceptance-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Hämta app
        uses: actions/checkout@v4
        with:
          path: app

      - name: Hämta Pipeline
        uses: actions/checkout@v4
        with:
          repository: simonbrundin/deployment-pipeline
          ref: refs/tags/v1
          path: pipeline

      - name: Kör Acceptance Phase
        uses: dagger/dagger-for-github@v8.3.0
        with:
          verb: call
          module: ./pipeline/dagger-modules/pipeline
          args: acceptance-phase --source-dir app/${{ inputs.source-dir }}
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
