name: Commit Phase

on:
  workflow_call:
    inputs:
      source-dir:
        required: false
        default: "."
        type: string
      image-name:
        required: false
        default: ""
        type: string
    secrets:
      DAGGER_CLOUD_TOKEN:
        required: false

jobs:
  commit-phase:
    runs-on: ubuntu-latest
    steps:
      - name: Hämta app
        uses: actions/checkout@v4
        with:
          path: app

      - name: Hämta Pipeline
        uses: actions/checkout@v4
        with:
          repository: simonbrundin/deployment-pipeline
          ref: refs/heads/main
          path: pipeline

      - name: Kör Commit Phase
        uses: dagger/dagger-for-github@v8.3.0
        with:
          verb: call
          module: ./dagger-modules/pipeline
          workdir: ./pipeline
          call: commit-phase --source-dir ../app/${{ inputs.source-dir }} --registry-address ${{ vars.REGISTRY_ADDRESS }} --image-name ${{ inputs.image-name || github.event.repository.name }} --username ${{ vars.REGISTRY_USERNAME }} --secret ${{ secrets.REGISTRY_PASSWORD }} --multi-arch true
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
